kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-acl-configurator-operator-consul-service
subjects:
  - kind: ServiceAccount
    name: consul-acl-configurator-operator
    namespace: consul
roleRef:
  kind: ClusterRole
  name: consul-acl-configurator-operator-consul-service
  apiGroup: rbac.authorization.k8s.io