apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: consul-auth-method-consul-service
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: consul-auth-method-consul-service
subjects:
  - kind: ServiceAccount
    name: consul-auth-method
    namespace: consul
