name: Setup TLS
description: Installs cert-manager and creates test issuer/certificate for TLS testing
runs:
  using: composite
  steps:
    - name: Describe nodes
      shell: bash
      run: |
        echo "::group::Describe nodes"
        kubectl describe nodes
        echo "::endgroup::"

    - name: Install cert-manager
      shell: bash
      run: |
        echo "::group::Install cert-manager"
        helm repo add jetstack https://charts.jetstack.io --force-update
        helm upgrade --install cert-manager jetstack/cert-manager --namespace cert-manager \
          --create-namespace --version v1.16.3 --set prometheus.enabled=true --set crds.enabled=true
        echo "::endgroup::"

    - name: Create cert-manager entities
      shell: bash
      run: |
        echo "::group::Create cert-manager entities"
        kubectl apply -f qubership-test-pipelines/resources/test-issuer.yaml
        sleep 10s
        kubectl apply -f qubership-test-pipelines/resources/test-certificate.yaml
        sleep 10s
        kubectl apply -f qubership-test-pipelines/resources/test-clusterissuer.yaml
        echo "::endgroup::"

    - name: Get cert-manager resources
      shell: bash
      run: |
        echo "::group::Get cert-manager resources"
        kubectl get pods -n cert-manager
        kubectl get secrets -n cert-manager
        kubectl get certificates -A
        echo "::endgroup::"

    - name: Get clusterissuer
      shell: bash
      run: |
        echo "::group::Get clusterissuer"
        kubectl get clusterissuer
        kubectl get clusterissuer test-clusterissuer -o yaml
        echo "::endgroup::"
