---

# Charts release configuration file example
# This file is used to update the version of the helm charts and images in the values.yaml file
# It is used in the helm-charts-release action
# ${release} is replaced with the release version provided in the workflow

charts:
  - name: qubership-opensearch
    chart_file: charts/helm/opensearch-service/Chart.yaml
    values_file: charts/helm/opensearch-service/values.yaml
    image:
      - ghcr.io/netcracker/qubership-opensearch-operator:${release}
      - ghcr.io/netcracker/qubership-opensearch-integration-tests:${release}
      - ghcr.io/netcracker/qubership-opensearch-transfer:${release}
      - ghcr.io/netcracker/qubership-opensearch-tls-init:${release}
