name: 'Custom GitHub Action'
description: 'A GitHub Action that installs services to kubernetes'
inputs:
  deploy_mode:
    description: 'Install or update'
    required: true
    default: 'upgrade'
  path_to_template:
    description: 'Path to template'
    required: true
  service_branch:
    description: 'branch name in repository with service'
    required: true
  pipeline_branch:
    description: 'name of branch with your pipeline in qubership-test-pipelines'
    required: true
    default: 'main'
  service_name:
    description: 'name with which service will be installed by helm'
    required: true
    default: 'consul'
  repository_name:
    description: 'name of repository with service'
    required: true
    default: 'qubership-consul'
  path_to_chart:
    description: 'path to helm chart in repository'
    required: true
    default: 'charts/helm/consul-service'
  components:
    description: 'list of components in which images should be replaced with images from the current branch'
    required: true
    default: 'integrationTests'
  namespace:
    description: 'namespase to install service'
    required: true
    default: 'consul'

runs:
  using: 'composite'
  steps:
    - name: Get values
      run: | 
        echo ${{inputs.path_to_template}} ${{inputs.service_branch}} ${{env.pipeline_branch}} ${{env.service_name}} ${{env.repository_name}} ${{env.path_to_chart}} ${{env.components}} ${{env.namespace}}
      shell: bash
    - name: Checkout pipeline
      uses: actions/checkout@v4
      with:
        ref: '${{env.pipeline_branch}}'
        repository: 'Netcracker/qubership-test-pipelines'
        path: 'qubership-test-pipelines'
    - name: Run helm_install action
      uses: Netcracker/qubership-test-pipelines/actions/shared/helm_deploy@update_actions
      with:
        deploy_mode: ${{inputs.deploy_mode}}
        path_to_template: ${{inputs.path_to_template}}
        service_branch: ${{inputs.service_branch}}
        pipeline_branch: ${{inputs.pipeline_branch}}
        service_name: ${{inputs.service_name}}
        repository_name: ${{inputs.repository_name}}
        path_to_chart: ${{inputs.path_to_chart}}
        components: ${{inputs.components}}
        namespace: ${{inputs.namespace}}