name: 'Collect Diagnostics Action'
description: 'A GitHub Action to collect logs and artifacts from Kubernetes namespace.'
inputs:
  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

  service_branch:
    description: |
      Branch in service repository
    required: false

  artifact_name:
    description: |
      Name of the artifact to be uploaded
    required: false
    default: ""

  monitoring_pipeline:
    description: |
      Only for Monitoring. Enable monitoring CRs checks (true) or disable them (false)
    required: false
    type: boolean
    default: false

  version:
    description: |
      Version from matrix to append to artifact name
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Create folder for artifacts
      shell: bash
      # language=bash
      run: mkdir -p artifacts

    - name: Get monitoring specific resources
      if: ${{ inputs.monitoring_pipeline == 'true' }}
      shell: bash
      # language=bash
      run: |
        set +e
        echo "Getting VictoriaMetrics specific resources..."
        kubectl get vmalertmanagers -n "${{inputs.namespace}}" -o yaml > artifacts/vmalertmanagers.yaml 2>/dev/null || true
        kubectl get vmalerts -n "${{inputs.namespace}}" -o yaml > artifacts/vmalerts.yaml 2>/dev/null || true
        kubectl get vmagent -n "${{inputs.namespace}}" -o yaml > artifacts/vmagent.yaml 2>/dev/null || true
        kubectl get vmsingles -n "${{inputs.namespace}}" -o yaml > artifacts/vmsingles.yaml 2>/dev/null || true
        kubectl get vmauths -n "${{inputs.namespace}}" -o yaml > artifacts/vmauths.yaml 2>/dev/null || true
        kubectl get PlatformMonitoring platformmonitoring -n ${{inputs.namespace}} -o yaml > artifacts/PlatformMonitoring.yaml 2>/dev/null || true

    - name: Get pods
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        # ▶️ Get pods
        file_name="artifacts/${{inputs.namespace}}_get_pods.txt"
        kubectl get pods -n "${{inputs.namespace}}"
        kubectl get pods -n "${{inputs.namespace}}" > "$file_name" 2>/dev/null || true

    - name: Get yaml from pods
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        # ▶️ Get yaml from pods
        file_name="artifacts/${{inputs.namespace}}_get_pods_yaml.txt"
        IFS=" " read -ra pods <<< "$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n "${{inputs.namespace}}" 2>/dev/null | tr "\n" " ")"
        echo "Yaml files from pods:" > "$file_name"
        for pod in "${pods[@]}"; do
            echo "$pod" >> "$file_name"
            kubectl get pod "$pod" -n "${{inputs.namespace}}" -o yaml >> "$file_name" 2>/dev/null || echo "⚠️ Failed to get yaml for $pod" >> "$file_name"
        done

    - name: Get events from namespace
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        # ▶️ Get events from namespace
        file_name="artifacts/${{inputs.namespace}}_get_events.txt"
        kubectl events -n "${{inputs.namespace}}" > "$file_name" 2>/dev/null || true

    - name: Get yaml from PVC
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        # ▶️ Get yaml from PVC
        file_name="artifacts/${{inputs.namespace}}_get_pvc_yaml.txt"
        kubectl get pvc -n "${{inputs.namespace}}" 2>/dev/null || true
        kubectl get pvc -n "${{inputs.namespace}}" -o yaml > "$file_name" 2>/dev/null || true

    - name: Get PV from namespace
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        # ▶️ Get PV from namespace
        file_name="artifacts/${{inputs.namespace}}_get_pv.txt"
        if kubectl get pv 2>/dev/null | grep -q "${{inputs.namespace}}"; then
          kubectl get pv | grep "${{inputs.namespace}}" > "$file_name"
          echo "✅ PV found and saved to $file_name"
        else
          echo "No PV found for namespace ${{inputs.namespace}}" > "$file_name"
          echo "ℹ️ No PV found for namespace ${{inputs.namespace}}"
        fi

    - name: Get logs from all containers in pods
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        # ▶️ Get logs from all containers in pods
        file_name=artifacts/${{ inputs.namespace }}_log_from_containers.txt
        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{ inputs.namespace }} 2>/dev/null | tr $'\n' ' ')
        echo "Logs from all containers in pods: " > $file_name

        # Array for pending containers "pod:container"
        declare -a pending=()

        # First pass: collect logs from ready containers, add unready ones to pending
        for pod in "${pods[@]}"; do
            IFS=' ' read -ra containers <<< $(kubectl get pod "$pod" -n ${{ inputs.namespace }} -o jsonpath="{.spec.containers[*].name}" 2>/dev/null || echo "")
            for container in "${containers[@]}"; do
                echo "Trying to get logs from ${container}"
                status=$(kubectl get pod "$pod" -n ${{ inputs.namespace }} -o jsonpath="{.status.containerStatuses[?(@.name==\"$container\")].state}" 2>/dev/null || echo "unknown")
                if [[ $status == *"running"* || $status == *"terminated"* ]]; then
                    echo "$pod $container" >> $file_name
                    kubectl logs "$pod" -n ${{ inputs.namespace }} -c "$container" >> $file_name 2>> $file_name || echo "⚠️ Failed to collect log for $pod $container" >> $file_name
                    echo '================================================================================' >> $file_name
                    echo "✅ Container (${container}) logs successfully added into $file_name"
                else
                    echo "ℹ️ Container (${container}) is not ready yet. Send it to pending."
                    pending+=("$pod:$container")
                    echo "$pod $container - added to pending (initial status: $status)" >> $file_name
                fi
            done
        done

        # ▶️ Waiting for pending with a general timeout
        echo "▶️ Waiting for pending with a general timeout"
        timeout=300
        start_time=$(date +%s)
        while [ ${#pending[@]} -gt 0 ]; do
            current_time=$(date +%s)
            if (( current_time - start_time > timeout )); then
                for item in "${pending[@]}"; do
                    IFS=':' read -r pod container <<< "$item"
                    echo "$pod $container - skipped (timed out waiting for readiness)"
                    echo '================================================================================'
                done
                break
            fi

            # Copy pending to modify the original
            declare -a current_pending=("${pending[@]}")
            pending=()
            for item in "${current_pending[@]}"; do
                IFS=':' read -r pod container <<< "$item"
                status=$(kubectl get pod "$pod" -n ${{ inputs.namespace }} -o jsonpath="{.status.containerStatuses[?(@.name==\"$container\")].state}" 2>/dev/null || echo "unknown")
                if [[ $status == *"running"* || $status == *"terminated"* ]]; then
                    echo "$pod $container" >> $file_name
                    kubectl logs "$pod" -n ${{ inputs.namespace }} -c "$container" >> $file_name 2>> $file_name || echo "⚠️ Failed to collect log for $pod $container" >> $file_name
                    echo '================================================================================' >> $file_name
                    echo "✅ Container (${container}) logs successfully added into $file_name"
                else
                    pending+=("$pod:$container")
                    echo "ℹ️ Container (${container}) is not ready yet. Send it to pending."
                fi
            done

            # If there are any pending ones left, wait before the next iteration
            if [ ${#pending[@]} -gt 0 ]; then
                sleep 5  # Wait 5 seconds before next check
            fi
        done

    - name: Get All
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        kubectl get all -n "${{inputs.namespace}}" 2>/dev/null || true

    - name: Get Secrets
      shell: bash
      # language=bash
      if: always()
      run: |
        set +e
        kubectl get secrets -n "${{inputs.namespace}}" 2>/dev/null || true

    - name: Generate artifact name
      if: always()
      shell: bash
      # language=bash
      run: |
        set +e
        # ▶️ Generate artifact name
        service_branch=$(echo "${{inputs.service_branch}}" | tr -d '[:space:]')
        service_branch="${service_branch//\//_}"
        echo matrix_version ${{inputs.version}}
        matrix_suffix=""
        if [[ -n "${{ inputs.version }}" ]]; then
          echo ${{ inputs.version }}
          matrix_suffix="${{inputs.version}}_"
        fi

        if [[ "${{inputs.artifact_name}}" != "" ]]; then
          artifact_name=${{inputs.artifact_name}}
          ARTIFACT_NAME=${artifact_name//\//_}_$(date -u +'%Y%m%d%H%M%S')
        else
          ARTIFACT_NAME="${{github.job}}_${{inputs.namespace}}_${service_branch}_${matrix_suffix}artifacts_$(date -u +"%Y%m%d%H%M%S")"
        fi
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: "${{env.ARTIFACT_NAME}}"
        path: artifacts/