name: 'Verify Installation Action'
description: 'A GitHub Action to verify Kubernetes deployments including status checks and test validation.'
inputs:
  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

  service_ready_max_retries:
    description: |
      Maximum retries for provisioner pod or custom resource to be completed
    required: true

  service_ready_retry_interval:
    description: |
      Delay between provisioner pod / CR check attempts (in seconds)
    required: true

  test_completion_max_retries:
    description: |
      Maximum verification retries for test pod to be completed
    required: true

  test_completion_retry_interval:
    description: |
      Delay between test pod check attempts
    required: true

  crd_list:
    description: |
      List of custom resource definitions for checking deploy status.
    required: false

  check_tests:
    description: |
      Enable test checks (true) or disable them (false)
    required: false
    type: boolean
    default: true

  monitoring_pipeline:
    description: |
      Only for Monitoring. Enable monitoring CRs checks (true) or disable them (false)
    required: false
    type: boolean
    default: false

  repository_name:
    description: |
      Name of the repository where the action is being executed. Used for monitoring specific checks.
    required: false
    default: ""

runs:
  using: "composite"
  steps:
    - name: Initialize error flag
      shell: bash
      # language=bash
      run: echo "ERROR_FLAG=false" >> $GITHUB_ENV

    - name: Check service is ready
      shell: bash
      # language=bash
      run: |
        # ▶️ Check service is ready
        chmod +x ./qubership-test-pipelines/scripts/check_cr.sh
        chmod +x ./qubership-test-pipelines/scripts/check_resources.sh

        echo "Checking CRDs: ${{inputs.crd_list}}"
        cr_success=false
        resources_success=false

        for i in {1..${{inputs.service_ready_max_retries}}}; do
          echo "Attempt $i/${{inputs.service_ready_max_retries}}"

          if [ "$cr_success" = "false" ]; then
            set +e
            ./qubership-test-pipelines/scripts/check_cr.sh "${{inputs.crd_list}}" "${{inputs.namespace}}"
            cr_exit_code=$?
            set -e

            case $cr_exit_code in
              0)
                echo "✅ CR check successful"
                cr_success=true
                break
                ;;
              1)
                echo "⏳ CR check in progress"
                echo -e "Retrying in ${{inputs.service_ready_retry_interval}} seconds...\n"
                sleep ${{inputs.service_ready_retry_interval}}
                ;;
              2)
                echo "::error:: ❌ CR check failed"
                echo "ERROR_FLAG=true" >> $GITHUB_ENV
                break
                ;;
            esac
          fi
        done
        if [[ "${{ inputs.monitoring_pipeline }}" == "true" ]]; then
          # ▶️ Check monitoring CRs statuses
          echo "Checking VictoriaMetrics CRs in namespace: ${{inputs.namespace}}"
          chmod +x ./qubership-test-pipelines/scripts/monitoring/check-vm-cr-statuses.sh
          echo $(pwd)
          echo "${{inputs.repository_name}}/.github/expected-vm-cr-statuses.json"
          cat "${{inputs.repository_name}}/.github/expected-vm-cr-statuses.json"
          ./qubership-test-pipelines/scripts/monitoring/check-vm-cr-statuses.sh ${{inputs.namespace}} ${{inputs.service_ready_max_retries}} ${{inputs.service_ready_retry_interval}} ${{inputs.repository_name}}/.github/expected-vm-cr-statuses.json ${{inputs.crd_list}}
        fi
        for i in {1..${{inputs.service_ready_max_retries}}}; do
          echo "Attempt $i/${{inputs.service_ready_max_retries}}"
          if [ "$resources_success" = "false" ]; then
            set +e
            ./qubership-test-pipelines/scripts/check_resources.sh "${{inputs.namespace}}"
            resources_exit_code=$?
            set -e

            if [ $resources_exit_code -eq 0 ]; then
              echo "✅ Resources checks successful"
              resources_success=true
              break
            elif [ $resources_exit_code -eq 1 ]; then
              echo "⏳ Some resources are not ready"
              echo "PODS:"
              kubectl get pods -n "${{inputs.namespace}}"
              sleep ${{inputs.service_ready_retry_interval}}
            fi
          fi
        done

          if [ "$cr_success" = "true" ] && [ "$resources_success" = "true" ]; then
            echo "✅ All checks completed successfully!"
          fi
          if [ "$cr_success" = "false" ]; then
            echo "::error:: ❌ CR check not successful after ${{inputs.service_ready_max_retries}} retries"
            echo "ERROR_FLAG=true" >> $GITHUB_ENV
          fi
          if [ "$resources_success" = "false" ]; then
            echo "::error:: ❌ Resources not ready after ${{inputs.service_ready_max_retries}} retries"
            echo "ERROR_FLAG=true" >> $GITHUB_ENV
          fi

    - name: Get logs from test pod
      if: ${{ inputs.check_tests == 'true' }}
      shell: bash
      # language=bash
      run: |
        # ▶️ Get logs from test pod
        chmod +x ./qubership-test-pipelines/scripts/check_tests.sh
        ls -la ./qubership-test-pipelines/scripts/check_tests.sh

        for i in $(seq 1 ${{inputs.test_completion_max_retries}}); do
          echo "Test check attempt $i/${{inputs.test_completion_max_retries}}"
          set +e
          ./qubership-test-pipelines/scripts/check_tests.sh "${{inputs.namespace}}"
          tests_exit_code=$?
          set -e

          case $tests_exit_code in
            0)
              echo "✅ Tests passed successfully"
              break
              ;;
            1)
              echo "⏳ Tests still in progress"
              ;;
            2)
              echo "::error:: ❌ Tests failed"
              echo "ERROR_FLAG=true" >> $GITHUB_ENV
              break
              ;;
          esac

          if [ $i -eq ${{inputs.test_completion_max_retries}} ]; then
            echo "::warning:: ⚠️ Tests not completed after ${{inputs.test_completion_max_retries}} retries"
            echo "ERROR_FLAG=true" >> $GITHUB_ENV
          else
            sleep ${{inputs.test_completion_retry_interval}}
          fi
        done

    - name: Check job status
      shell: bash
      # language=bash
      run: |
        # ▶️ Check deploy status
        if [[ "${{ env.ERROR_FLAG }}" == "true" ]]; then
          echo "::error:: ❌ Service was installed with errors!"
          exit 1
        else
          echo "✅ Service installation completed successfully"
        fi
