name: 'Verify Installation Action'
description: 'A GitHub Action to verify Kubernetes deployments including status checks, log collection, and test validation.'
inputs:
  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

  max_attempts:
    description: |
      Maximum verification retries for test pod to be completed
    required: true

  timeout:
    description: |
      Delay between test pod check attempts
    required: true

  max_attempts_for_provisioner:
    description: |
      Maximum retries for provisioner pod to be completed
    required: true

  timeout_for_provisioner:
    description: |
      Delay between provisioner pod check attempts
    required: true

  service_branch:
    description: |
      Branch in service repository
    required: false

runs:
  using: 'composite'
  steps:
    - name: Create folder for artifacts
      run: mkdir -p artifacts
      shell: bash

    - name: Wait pods is ready
      run: |
        # ▶️ Wait pods is ready
        kubectl wait pod --all --for=condition=Ready -n=${{inputs.namespace}} --timeout 200s
      shell: bash
      continue-on-error: true

    - name: Get pods
      run: |
        # ▶️ Get pods
        kubectl get pods -n ${{inputs.namespace}}
        file_name=artifacts/${{inputs.namespace}}_get_pods.txt
        kubectl get pods -n ${{inputs.namespace}} > $file_name
      shell: bash

    - name: Get yaml from pods
      run: |
        # ▶️ Get yaml from pods
        file_name=artifacts/${{inputs.namespace}}_get_pods_yaml.txt
        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
        echo "Yaml files from pods: " > $file_name
        for pod in "${pods[@]}"; do
            echo $pod >> $file_name
            kubectl get pod "$pod" -n ${{inputs.namespace}} -o yaml >> $file_name
        done
      shell: bash

    - name: Get events from namespace
      run: |
        # ▶️ Get events from namespace
        file_name=artifacts/${{inputs.namespace}}_get_events.txt
        kubectl events -n ${{inputs.namespace}} > $file_name
      shell: bash

    - name: Get PVC from namespace
      run: |
        # ▶️ Get PVC from namespace
        kubectl get pvc -n ${{inputs.namespace}}
        file_name=artifacts/${{inputs.namespace}}_get_pvc.txt
        kubectl get pvc -n ${{inputs.namespace}} > $file_name
      shell: bash

    - name: Get yaml from PVC
      run: |
        # ▶️ Get yaml from PVC
        file_name=artifacts/${{inputs.namespace}}_get_pvc_yaml.txt
        kubectl get pvc -n ${{inputs.namespace}} -o yaml > $file_name
      shell: bash

    - name: Get PV from namespace
      run: |
        # ▶️ Get PV from namespace
        kubectl get pv | grep ${{inputs.namespace}}
        file_name=artifacts/${{inputs.namespace}}_get_pv.txt
        kubectl get pv | grep ${{inputs.namespace}} > $file_name
      shell: bash

    - name: Get yaml from PV
      run: |
        # ▶️ Get yaml from PV
        file_name=artifacts/${{inputs.namespace}}_get_pv_yaml.txt
        kubectl get pv -o yaml > $file_name
      shell: bash

    - name: Get status provisioner logs
      run: |
        # ▶️ Get status provisioner logs
        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
        for pod in "${pods[@]}"; do
          if [[ $pod == *"provisioner"* ]]; then
            provisioner_pod=$pod
          fi
        done
        if ! [[ $provisioner_pod ]]; then
          echo provisioner pod is not found
          exit 0
        fi
        echo "provisioner_pod=$provisioner_pod"
        for i in {1..${{inputs.max_attempts_for_provisioner}}}; do
          status=$(kubectl get pod $provisioner_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
          if [[ "$status" == 'Succeeded' ]]; then
            break
          fi
          sleep ${{inputs.timeout_for_provisioner}}
        done
        if [[ "$status" != 'Succeeded' ]]; then
          echo $provisioner_pod pod has not Succeeded status
        fi
        echo PROVISIONER LOGS:
        kubectl logs $provisioner_pod -n ${{inputs.namespace}}
        logs=$(kubectl logs $provisioner_pod -n ${{inputs.namespace}})
        if [[ $logs != *"Failed components statuses are []"* ]]; then
          echo Not all components are in succeed status after ${{inputs.max_attempts_for_provisioner}} attempts
          echo PODS:
          kubectl get pods -n ${{inputs.namespace}}
          exit 1
        fi
      shell: bash
      continue-on-error: true

    - name: Get logs from all containers in pods
      run: |
        # ▶️ Get logs from all containers in pods
        file_name=artifacts/${{inputs.namespace}}_log_from_containers.txt
        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
        echo "Logs from all containers in pods: " > $file_name
        for pod in "${pods[@]}"; do
            IFS=' ' read -ra containers <<< $(kubectl get pod "$pod" -n ${{inputs.namespace}} -o jsonpath="{.spec.containers[*].name}")
            for container in "${containers[@]}"; do
              echo $pod $container >> $file_name
              kubectl logs "$pod" -n ${{inputs.namespace}} -c "$container" >> $file_name
              echo '================================================================================' >> $file_name
            done
        done
      shell: bash

    - name: Get logs from test pod
      run: |
        # ▶️ Get logs from test pod
        file_name=artifacts/${{inputs.namespace}}_tests.txt
        IFS=' ' read -ra pods <<< $(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{inputs.namespace}} | tr $'\n' ' ')
        for pod in "${pods[@]}"; do
          if [[ $pod == *"tests"* ]]; then
            test_pod=$pod
          fi
        done
        if ! [[ $test_pod ]]; then
          echo There is no test pod
          exit 0
        fi
        echo "test_pod=$test_pod"
        for i in {1..${{inputs.max_attempts}}}; do
          status=$(kubectl get pod $test_pod -n ${{inputs.namespace}} -o jsonpath="{.status.phase}")
          echo '>>>'
          kubectl get pod $test_pod -n ${{inputs.namespace}}
          kubectl logs $test_pod -n ${{inputs.namespace}}
          echo '<<<'
          if [[ "$status" == 'Running' ]]; then
            break
          fi
          sleep ${{inputs.timeout}}
        done
        for i in {1..${{inputs.max_attempts}}}; do
          logs=$(kubectl logs $test_pod -n ${{inputs.namespace}})
          if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
            kubectl logs $test_pod -n ${{inputs.namespace}} > $file_name
            break
          fi
          sleep ${{inputs.timeout}}
        done
        echo 'TEST LOGS:'
        kubectl logs $test_pod -n ${{inputs.namespace}}
        if [[ $logs == *"| FAIL |"* ]]; then
          exit 1
        fi
      shell: bash

    - name: Generate artifact name
      if: always()
      run: |
        # ▶️ Generate artifact name
        release_name=$(echo ${{inputs.service_branch}})
        if [[ $release_name ]]; then
          release_name=$(echo "_$release_name" | tr '/' '_')
        fi
        ARTIFACT_NAME=${{github.job}}_${{inputs.namespace}}${release_name}_artifacts_$(date -u +'%Y%m%d%H%M%S')
        echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV
      shell: bash

    - name: Upload artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: ${{env.ARTIFACT_NAME}}
        path: artifacts/
