kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-acl-configurator-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: consul-service
    meta.helm.sh/release-namespace: consul-service
subjects:
  - kind: ServiceAccount
    name: consul-acl-configurator-operator
    namespace: consul-service
roleRef:
  kind: ClusterRole
  name: consul-acl-configurator-operator
  apiGroup: rbac.authorization.k8s.io
