name: "Helm deploy Action for Monitoring"
description: "GitHub Action for install/upgrade Consul using Helm"
inputs:
  deploy_mode:
    description: 'See helm_deploy.deploy_mode'
    required: true
    default: 'install'
  restricted:
    description: 'See helm_deploy.restricted'
    required: true
    default: 'false'
  path_to_template:
    description: 'See helm_deploy.path_to_template'
    required: false
    default: 'templates/monitoring/vm_with_smoke_at.yml'
  service_branch:
    description: 'See helm_deploy.service_branch'
    required: true
    default: 'main'
  service_name:
    description: 'See helm_deploy.service_name'
    required: true
    default: 'monitoring'
  repository_name:
    description: 'See helm_deploy.repository_name'
    required: true
    default: 'qubership-monitoring-operator'
  path_to_chart:
    description: 'See helm_deploy.path_to_chart'
    required: true
    default: 'charts/qubership-monitoring-operator'
  components:
    description: 'See helm_deploy.components'
    required: true
    default: ''
  namespace:
    description: 'See helm_deploy.namespace'
    required: true
    default: 'monitoring'

runs:
  using: 'composite'
  steps:
    - name: Run helm_install action for Monitoring
      uses: ./qubership-test-pipelines/actions/shared/helm_deploy
      with:
        deploy_mode: ${{inputs.deploy_mode}}
        restricted: ${{inputs.restricted}}
        path_to_template: ${{inputs.path_to_template}}
        service_branch: ${{inputs.service_branch}}
        service_name: ${{inputs.service_name}}
        repository_name: ${{inputs.repository_name}}
        path_to_chart: ${{inputs.path_to_chart}}
        components: ${{inputs.components}}
        namespace: ${{inputs.namespace}}

    - name: get pods
      run: |
        sleep 30s
        kubectl get pods -n monitoring
      shell: bash
