name: 'Create Kubernetes cluster Action'
description: 'A GitHub Action that creates Kubernetes cluster using Kind'
inputs:
  path_to_template:
    description: 'A path to template of kind-cluster layout'
    required: true
    default: 'qubership-test-pipelines/kind-configs/kind-multi-node.yaml'
runs:
  using: 'composite'
  steps:
      - name: Get info
        shell: bash
        # language=bash
        run: |
          free -h
          echo '================================================================================'
          lscpu
          echo '================================================================================'
          lsblk
          echo '================================================================================'
          sysctl vm.max_map_count
      - name: Install kind
        shell: bash
        # language=bash
        run: |
          echo Download kind
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64
          chmod +x ./kind
          # sudo mv ./kind /usr/local/bin/kind
      - name: Delete kind
        shell: bash
        # language=bash
        run: |
          ./kind get clusters
          for node in kind-worker kind-control-plane2 kind-external-load-balancer kind-control-plane kind-control-plane3 kind-worker3 kind-worker2; do
            if docker ps -a --format '{{.Names}}' | grep -q "^${node}$"; then
              docker rm -f -v "$node"
            fi
          done
          ./kind delete cluster --name kind || true
      - name: Run kind
        shell: bash
        # language=bash
        run: >-
          ./kind create cluster
          --image kindest/node:v1.32.2
          --config ${{ inputs.path_to_template }}
          --wait 5m
        #! check kubernetes version is actual
