name: 'Create Kubernetes cluster Action'
description: 'A GitHub Action that creates Kubernetes cluster using Kind'
runs:
  using: 'composite'
  steps:
      - name: Get info
        shell: bash
        # language=bash
        run: |
          free -h
          echo '================================================================================'
          lscpu
          echo '================================================================================'
          lsblk
      - name: Install kind
        shell: bash
        # language=bash
        run: |
          echo Download kind
          [ $(uname -m) = x86_64 ] && curl -Lo ./kind https://kind.sigs.k8s.io/dl/v0.25.0/kind-linux-amd64
          chmod +x ./kind
          # sudo mv ./kind /usr/local/bin/kind
      - name: Run kind
        shell: bash
        # language=bash
        run: >-
          ./kind create cluster
          --image kindest/node:v1.32.2
          --config qubership-test-pipelines/kind-configs/kind-multi-node.yaml
          --wait 5m
        #! check kubernetes version is actual
