name: Get Certs Action
description: GitHub Action to get certs from secret
inputs:
  job_result:
    description: |
      Result of job for which we check the status
    required: true

runs:
  using: composite
  steps:
    - name: Check job status
      shell: bash
      env:
        JOB_RESULT: ${{ inputs.job_result }}
      # language=bash
      run: |
        # ▶️ Check job status
        echo "Job status: ${JOB_RESULT}"
        if [[ "${JOB_RESULT}" == "success" || "${JOB_RESULT}" == "skipped" ]]; then
          exit 0
        else
          exit 1
        fi
