name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
#inputs:
#  namespace:
#    description: 'namespace where service is installed'
#    required: true

runs:
  using: 'composite'
  steps:
    - name: Get pods
      run: 'kubectl get pods -n ${{env.namespace}}'
      shell: bash
    - name: Get logs
      run: |
        pods=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}}  | tr -s '\r\n' ' ')
        IFS=$' ' read -a pods_list <<< "$pods"
        echo "$pods"
        for pod in "${pods_list[@]}"; do
          if [[ $pod == *"tests"* ]]; then
            test_pod=$pod
          fi
          if [[ $pod == *"provisioner"* ]]; then
            provisioner_pod=$pod
          fi
        done
        echo "test_pod=$test_pod"
        for i in {1..${{env.max_attempts}}}; do
          status=$(kubectl get pod $test_pod -n ${{env.namespace}} -o jsonpath="{.status.phase}")
          echo "status=$status"
          if [[ "$status" == 'Running' ]]; then
            break
          fi
          sleep ${{env.timeout}}
        done
        for i in {1..${{env.max_attempts}}}; do
          logs=$(kubectl logs $test_pod -n ${{env.namespace}})
          if [[ $logs == *"Report: /opt/robot/output/report.html"* ]]; then
            break
          fi
          sleep ${{env.timeout}}
        done
        echo 'TEST LOGS: '
        kubectl logs $test_pod -n ${{env.namespace}}
        if [[ $logs == *"| FAIL |"* ]]; then
          exit 1
        fi
      shell: bash
