operator:
  image: ghcr.io/netcracker/qubership-mongodb-operator:main
  initImage: ghcr.io/netcracker/qubership-credential-manager:v0.0.15
mongodb:
  install: true
  customDataRSParameters:
    - logLevel=0
  storage:
    size: 4Gi
    storageClasses:
      - standard
prometheusExporter:
  install: false
DEPLOY_W_HELM: true
