name: Get CRD names
inputs:
  crd_location:
    description: |
      Location of CRDs
      # Example:
      # from https://github.com/Netcracker/qubership-kafka
      # if checked out to qubership-kafka directory, then
      # 'qubership-kafka/operator/charts/helm/kafka-service/crds'
    required: true
outputs:
  crd_names:
    value: ${{ steps.get_crds.outputs.crd_names }}
runs:
  using: "composite"
  steps:
    - name: Get CRDs
      id: get_crds
      shell: bash
      run: |
        # ▶️ Get CRDs
        yamls=$(find ${{inputs.crd_location}} -type f -name "*.yaml" -or -name "*.yml")
        CRDS_ARRAY=()
        for yaml in ${yamls}; do
          yml_kind=$(yq e '.kind' $yaml)
          if [ "$yml_kind" == "CustomResourceDefinition" ]; then
            crd_name=$(yq e '.metadata.name' $yaml)
            CRDS_ARRAY+=$crd_name
          fi
        done
        CRDS=${CRDS_ARRAY[*]}
        echo "ℹ️ CRDs: '$CRDS'"
        echo "crd_names=${CRDS}" >> $GITHUB_OUTPUT
      continue-on-error: true
