kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: consul-acl-configurator-operator
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: consul-service
    meta.helm.sh/release-namespace: consul-service
rules:
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
      - statefulsets
      - daemonsets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - pods
      - configmaps
      - services
      - persistentvolumeclaims
      - secrets
    verbs:
      - get
      - create
      - list
      - update
      - watch
      - patch
      - delete
  - apiGroups:
      - qubership.org
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
