apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: consul-connect-injector-authmethod-role
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    meta.helm.sh/release-name: consul-service
    meta.helm.sh/release-namespace: consul-service
rules:
  - apiGroups: [""]
    resources:
      - serviceaccounts
    verbs:
      - get
