name: 'Custom GitHub Action'
description: 'A GitHub Action that installs services to kubernetes'
inputs:
  path_to_template:
    description: 'Path to template'
    required: true
  service_branch:
    description: 'branch with release'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Checkout pipeline
      uses: actions/checkout@v4
      with:
        ref: 'restricted_install'
        repository: 'Netcracker/qubership-test-pipelines'
        path: 'qubership-test-pipelines'

    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: '${{inputs.service.branch}}'
        repository: 'Netcracker/${{env.repository_name}}'
        path: '${{env.repository_name}}'

    - name: Create namespaces
      run: kubectl create namespace ${{env.namespace}}
      shell: bash

    - name: Create ClusterRoles
      run: |
        kubectl create -f qubership-test-pipelines/restricted/${{env.service_name}}/clusterRoles
      shell: bash

    - name: Create ClusterRoleBindings
      run: |
        kubectl create -f qubership-test-pipelines/restricted/${{env.service_name}}/clusterRoleBindings
      shell: bash

    - name: Create CRD
      run: |
        kubectl create -f ${{env.repository_name}}/${{env.path_to_chart}}/crds
        kubectl get CustomResourceDefinition consulacls.qubership.org -n consul -oyaml
      shell: bash

    - name: Get CRD
      run: kubectl get crd -n consul
      shell: bash

# Create Restriced Role and RB

#    - name: Create service account
#      run: kubectl create -f qubership-test-pipelines/restricted/restricted-sa.yml
#      shell: bash

    - name: Install Openssl
      run: |
        sudo apt install openssl
      shell: bash

    - name: Generate Private Key
      run: |
        openssl genrsa -out restricted.key 2048
      shell: bash

    - name: Generate CSR
      run: |
        openssl req -new -key restricted.key -out restricted.csr -subj "/CN=restricted/O=dev-team"
      shell: bash

    - name: Create CSR Object in Kubernetes
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: certificates.k8s.io/v1
        kind: CertificateSigningRequest
        metadata:
          name: restricted-csr
        spec:
          request: $(cat restricted.csr | base64 | tr -d '\n')
          signerName: kubernetes.io/kube-apiserver-client
          usages:
          - client auth
        EOF
      shell: bash

    - name: Approve CSR
      run: kubectl certificate approve restricted-csr
      shell: bash

    - name: Retrieve Certificate
      run: kubectl get csr restricted-csr -o jsonpath='{.status.certificate}' | base64 --decode > restricted.crt
      shell: bash

    - name: Create role
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: Role
        metadata:
          namespace: consul
          name: restricted-role
        rules:
        - apiGroups: [""]
          resources: ["pods"]
          verbs: ["get", "list", "watch"]
        EOF
      shell: bash

    - name: Create RoleBindings
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: rbac.authorization.k8s.io/v1
        kind: RoleBinding
        metadata:
          name: restricted-role-binding
          namespace: consul
        subjects:
        - kind: User
          name: restricted
          apiGroup: rbac.authorization.k8s.io
        roleRef:
          kind: Role
          name: restricted-role
          apiGroup: rbac.authorization.k8s.io
        EOF
      shell: bash

    - name: get config
      run: kubectl config view
      shell: bash

    - name: Add User Configuration
      run: kubectl config set-credentials restricted --client-certificate=restricted.crt --client-key=restricted.key
      shell: bash

    - name: Create Context for User
      run: kubectl config set-context restricted-context --cluster=kind-kind --namespace=consul --user=restricted
      shell: bash

    - name: Use Context
      run: kubectl config use-context restricted-context
      shell: bash

#    - name: Update config
#      run: |
#        restricted_token=$(kubectl get secret restricted-token -ojsonpath='{.data.token}')
#        echo $restricted_token
#        kubectl config set-credentials restricted-sa --token=$restricted_token
#        kubectl config set-context restricted --cluster=kind-kind --user=restricted-sa
#        kubectl config use-context restricted
#      shell: bash

#    - name: Update config
#      run: |
#        restricted_token=$(kubectl get secret restricted-token -ojsonpath='{.data.token}')
#        echo $restricted_token
#        #kubectl config set-credentials restricted-sa --token=$restricted_token
#        #kubectl config set-context --user=restricted-sa --current
#      shell: bash


    - name: get config
      run: kubectl config view --raw
      shell: bash

    - name: get pods
      run: kubectl get pods
      shell: bash

#    - name: get pods
#      run: kubectl get pods -n default
#      shell: bash

      #-----------------------------------------------------
    - name: Copy template
      run: |
        cp qubership-test-pipelines/${{inputs.path_to_template}} ${{env.repository_name}}/${{env.path_to_chart}}
      shell: bash

    - name: Update images
      run: python qubership-test-pipelines/python/update_images.py --service_branch='${{inputs.service_branch}}'
      shell: bash

    - name: Install service with helm
      run: |
        IFS=$'/' read -a path <<< "$${{inputs.path_to_template}}"
        template_name=${path[-1]}
        echo $template_name
        cd ${{env.repository_name}}/${{env.path_to_chart}}
        helm install ${{env.service_name}} . -f $template_name -n ${{env.namespace}} $SET_NEW_IMAGES --timeout 10m
      shell: bash
