jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: Clean [${release_version}], Upgrade to [${service_branch}]
    sequence: upgrade
    restricted: false
    install:
      version: ${release_version}
      template: templates/cassandra-service/sample.yaml
      template_operator: templates/cassandra-service/sample.yaml
      template_services: templates/cassandra-service/sample_sup.yaml
      artifact_name: Clean_${release_version}_Upgrade_CURRENT
    upgrade:
      version: ${service_branch}
      template_operator: templates/cassandra-service/sample.yaml
      template_services: templates/cassandra-service/sample_sup.yaml
      artifact_name: Clean_${release_version}_Upgrade_CURRENT
  ## ===============================================================================

  - name: Clean [${service_branch}], Update [${service_branch}] Diff Params
    sequence: upgrade
    restricted: false
    install:
      version: ${service_branch}
      template: templates/cassandra-service/sample.yaml
      template_operator: templates/cassandra-service/sample.yaml
      template_services: templates/cassandra-service/sample_sup.yaml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params
    upgrade:
      version: ${service_branch}
      template_operator: templates/cassandra-service/sample.yaml
      template_services: templates/cassandra-service/sample_sup_updated.yaml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params

  - name: Clean [${service_branch}] in TLS
    sequence: install
    restricted: false
    tls: true
    install:
      version: ${service_branch}
      template: templates/cassandra-service/sample_tls.yaml
      template_operator: templates/cassandra-service/sample_tls.yaml
      template_services: templates/cassandra-service/sample_sup_tls.yaml
      artifact_name: Clean_CURRENT_TLS

  - name: Clean [${service_branch}] on S3 storage
    sequence: install
    restricted: false
    install:
      version: ${service_branch}
      template: templates/cassandra-service/sample.yaml
      template_operator: templates/cassandra-service/sample.yaml
      template_services: templates/cassandra-service/sample_sup_s3.yaml
      s3: true
      artifact_name: Clean_CURRENT_S3

  - name: Clean [${service_branch}] W/O Backup and Dbaas
    sequence: install
    restricted: false
    install:
      version: ${service_branch}
      template: templates/cassandra-service/sample.yaml
      template_operator: templates/cassandra-service/sample.yaml
      template_services: templates/cassandra-service/sample_sup_without_components.yaml
      artifact_name: Clean_CURRENT_WO_Backup_Dbaas

  - name: Clean [${service_branch}] Restricted
    sequence: install
    restricted: true
    install:
      version: ${service_branch}
      template: templates/cassandra-service/sample.yaml
      template_operator: templates/cassandra-service/sample.yaml
      template_services: templates/cassandra-service/sample_sup.yaml
      artifact_name: Clean_CURRENT_Restricted
