jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: "Clean [${release_version}], Upgrade to [${service_branch}]"
    kafka_install_version: '${release_version}'
    kafka_template: "templates/kafka-service/kafka_clean_sc.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc.yml"
    kafka_upgrade_version: '${service_branch}'
    kafka_upgrade_template: "templates/kafka-service/kafka_clean_sc.yml"
    kafka_service_upgrade_template: "templates/kafka-service/kafka_clean_sc.yml"
    sequence: upgrade
    zookeeper: false
    zookeeper_template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    artifact_name: "Clean_${release_version}_Upgrade"
  ## ===============================================================================
  - name: Clean [${service_branch}]. Update [${service_branch}] Diff Params in Kraft mode
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_kraft_mode.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_kraft_mode.yml"
    kafka_upgrade_version: '${service_branch}'
    kafka_upgrade_template: "templates/kafka-service/kafka_update_kraft_mode.yml"
    kafka_service_upgrade_template: "templates/kafka-service/kafka_update_kraft_mode.yml"
    sequence: upgrade
    zookeeper: false
    artifact_name: "Clean_Update_Diff_Params_Kraft_mode"

  - name: Clean [${service_branch}] with Zookeeper in TLS. Migrate [${service_branch}] to scheme without Zookeeper in TLS
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
    kafka_upgrade_version: '${service_branch}'
    kafka_upgrade_template: "templates/kafka-service/kafka_clean_sc_tls.yml"
    kafka_service_upgrade_template: "templates/kafka-service/kafka_clean_sc_tls.yml"
    sequence: upgrade
    zookeeper: true
    tls: true
    zookeeper_template: "templates/zookeeper-service/zookeeper_install_tls_APP_k8s.yml"
    artifact_name: "Clean_Zookeeper_Migrate_Kraft_mode"

  - name: Clean [${service_branch}] in non-TLS
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc.yml"
    sequence: install
    zookeeper: false
    zookeeper_template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    artifact_name: "Clean_non-TLS"

  - name: Clean [${service_branch}] in TLS
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_tls.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_tls.yml"
    sequence: install
    zookeeper: false
    tls: true
    zookeeper_template: "templates/zookeeper-service/zookeeper_install_tls_APP_k8s.yml"
    artifact_name: "Clean_TLS"

  - name: Clean [${service_branch}] on S3 storage
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_s3.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_s3.yml"
    sequence: install
    zookeeper: false
    zookeeper_template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    storage: s3
    artifact_name: "Clean_S3"
