jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: Clean [${release_version}]. Upgrade to [${service_branch}]
    sequence: upgrade
    install:
      version: ${release_version}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_${release_version}_Kraft_Upgrade_CURRENT_Kraft
    upgrade:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_${release_version}_Kraft_Upgrade_CURRENT_Kraft
  ## ===============================================================================
#  - purpose: automation
#    name: "Clean [${service_branch}] with Zookeeper in TLS. Migrate to [${service_branch}] without Zookeeper in TLS"
#    sequence: upgrade
#    install:
#      version: '${service_branch}'
#      kafka_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#      kafka_service_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#      tls: true
#      zookeeper: true
#      zookeeper_template: "templates/zookeeper-service/zookeeper_install_tls_APP_k8s.yml"
#      artifact_name: "Clean_${service_branch}_Zookeeper_Migrate_${release_version}_Kraft"
#    upgrade:
#      version: '${service_branch}'
#      kafka_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#      kafka_service_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#      artifact_name: "Clean_${service_branch}_Zookeeper_Migrate_${release_version}_Kraft"

#  - purpose: automation
#    name: "Clean [${release_version}] with Zookeeper in TLS. Migrate to [${release_version}] without Zookeeper in TLS. Upgrade to [${service_branch}] in TLS"
#    sequence: migrate
#    install:
#      version: '${release_version}'
#      kafka_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#      kafka_service_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#      tls: true
#      zookeeper: true
#      zookeeper_template: "templates/zookeeper-service/zookeeper_install_tls_APP_k8s.yml"
#      artifact_name: "Clean_${release_version}_Zookeeper_Migrate_${release_version}_Kraft_Upgrade_CURRENT_Kraft"
#    migrate:
#      version: '${release_version}'
#      kafka_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#      kafka_service_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#      artifact_name: "Clean_${release_version}_Zookeeper_Migrate_${release_version}_Kraft_Upgrade_CURRENT_Kraft"
#    upgrade:
#      version: '${service_branch}'
#      kafka_template: "templates/kafka-service/kafka_clean_sc_kraft_tls.yml"
#      kafka_service_template: "templates/kafka-service/kafka_clean_sc_kraft_tls.yml"
#      artifact_name: "Clean_${release_version}_Zookeeper_Migrate_${release_version}_Kraft_Upgrade_CURRENT_Kraft"

  - name: Clean [${service_branch}]. Update [${service_branch}] Diff Params in Kraft
    sequence: upgrade
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params_Kraft
    upgrade:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_update_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_update_sc_kraft.yml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params_Kraft

  - name: Clean [${service_branch}] in non-TLS
    sequence: install
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_CURRENT_non-TLS

  - name: Clean [${service_branch}] in TLS
    sequence: install
    tls: true
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft_tls.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft_tls.yml
      artifact_name: Clean_CURRENT_TLS

  - name: Clean [${service_branch}] on S3 storage
    sequence: install
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft_s3.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft_s3.yml
      s3: true
      artifact_name: Clean_CURRENT_S3
