jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: Clean [${release_version}]. Upgrade to [${service_branch}]
    sequence: upgrade
    install:
      version: ${release_version}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_${release_version}_Kraft_Upgrade_CURRENT_Kraft
    upgrade:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_${release_version}_Kraft_Upgrade_CURRENT_Kraft

  - name: Clean [${service_branch}]. Update [${service_branch}] Diff Params in Kraft
    sequence: upgrade
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params_Kraft
    upgrade:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_update_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_update_sc_kraft.yml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params_Kraft

  - name: Clean [${service_branch}] in non-TLS
    sequence: install
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft.yml
      artifact_name: Clean_CURRENT_non-TLS

  - name: Clean [${service_branch}] in TLS
    sequence: install
    tls: true
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft_tls.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft_tls.yml
      artifact_name: Clean_CURRENT_TLS

  - name: Clean [${service_branch}] on S3 storage
    sequence: install
    install:
      version: ${service_branch}
      kafka_template: templates/kafka-service/kafka_clean_sc_kraft_s3.yml
      kafka_service_template: templates/kafka-service/kafka_clean_sc_kraft_s3.yml
      s3: true
      artifact_name: Clean_CURRENT_S3
