jobs:
  - name: Clean [${service_branch}] - Hardening Check
    kafka_install_version: ${service_branch}
    kafka_template: templates/kafka-service/kafka_clean_sc_hardening.yml
    kafka_service_template: templates/kafka-service/kafka_clean_sc_hardening.yml
    sequence: install
    artifact_name: Clean_CURRENT_Hardening_Check
    monitoring: false
