jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: "Clean [${release_version}]. Upgrade to [${service_branch}]"
    kafka_install_version: '${release_version}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    kafka_upgrade_version: '${service_branch}'
    kafka_upgrade_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    kafka_service_upgrade_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    sequence: upgrade
    artifact_name: "Clean_${release_version}_Kraft_Upgrade_CURRENT_Kraft"
    test_tags: kafka
  ## ===============================================================================
#  - purpose: automation
#    name: "Clean [${service_branch}] with Zookeeper in TLS. Migrate to [${service_branch}] without Zookeeper in TLS"
#    kafka_install_version: '${service_branch}'
#    kafka_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#    kafka_service_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#    kafka_upgrade_version: '${service_branch}'
#    kafka_upgrade_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#    kafka_service_upgrade_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#    sequence: upgrade
#    tls: true
#    zookeeper: true
#    zookeeper_template: "templates/zookeeper-service/zookeeper_install_tls_APP_k8s.yml"
#    artifact_name: "Clean_${service_branch}_Zookeeper_Migrate_${release_version}_Kraft"

#  - purpose: automation
#    name: "Clean [${release_version}] with Zookeeper in TLS. Migrate to [${release_version}] without Zookeeper in TLS. Upgrade to [${service_branch}] in TLS"
#    kafka_install_version: '${release_version}'
#    kafka_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#    kafka_service_template: "templates/kafka-service/kafka_clean_sc_zoo_tls.yml"
#    kafka_migrate_version: '${release_version}'
#    kafka_migrate_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#    kafka_service_migrate_template: "templates/kafka-service/kafka_migration_sc_kraft_tls.yml"
#    kafka_upgrade_version: '${service_branch}'
#    kafka_upgrade_template: "templates/kafka-service/kafka_clean_sc_kraft_tls.yml"
#    kafka_service_upgrade_template: "templates/kafka-service/kafka_clean_sc_kraft_tls.yml"
#    sequence: migrate
#    tls: true
#    zookeeper: true
#    zookeeper_template: "templates/zookeeper-service/zookeeper_install_tls_APP_k8s.yml"
#    artifact_name: "Clean_${release_version}_Zookeeper_Migrate_${release_version}_Kraft_Upgrade_CURRENT_Kraft"

  - name: "Clean [${service_branch}]. Update [${service_branch}] Diff Params in Kraft"
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    kafka_upgrade_version: '${service_branch}'
    kafka_upgrade_template: "templates/kafka-service/kafka_update_sc_kraft.yml"
    kafka_service_upgrade_template: "templates/kafka-service/kafka_update_sc_kraft.yml"
    sequence: upgrade
    artifact_name: "Clean_CURRENT_Update_CURRENT_Diff_Params_Kraft"
    test_tags: kafka

  - name: "Clean [${service_branch}] in non-TLS"
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_kraft.yml"
    sequence: install
    artifact_name: "Clean_CURRENT_non-TLS"
    test_tags: kafka

  - name: "Clean [${service_branch}] with monitoring"
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_kraft_monitoring.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_kraft_monitoring.yml"
    sequence: install
    artifact_name: "Clean_CURRENT_non-TLS"
    test_tags: kafka
    monitoring: true

  - name: "Clean [${service_branch}] in TLS"
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_kraft_tls.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_kraft_tls.yml"
    sequence: install
    tls: true
    artifact_name: "Clean_CURRENT_TLS"
    test_tags: kafka

  - name: "Clean [${service_branch}] on S3 storage"
    kafka_install_version: '${service_branch}'
    kafka_template: "templates/kafka-service/kafka_clean_sc_kraft_s3.yml"
    kafka_service_template: "templates/kafka-service/kafka_clean_sc_kraft_s3.yml"
    sequence: install
    storage: s3
    artifact_name: "Clean_CURRENT_S3"
    test_tags: kafka
