jobs:
  ## Upgrade from previous releases to current
  - name: Clean [${service_branch}], Upgrade [${service_branch}] Diff Params
    sequence: clean
    restricted: false
    install:
      version: ${service_branch}
      template: templates/monitoring/vm_with_smoke_and_simple_test_allure.yml
      artifact_name: Clean_${service_branch}_Upgrade_${service_branch}_Diff_Params
      allure: true
    upgrade:
      version: ${service_branch}
      template: templates/monitoring/values_test.yml
      artifact_name: Clean_${service_branch}_Upgrade_${service_branch}_Diff_Params
