jobs:
  - name: Clean [${service_branch}] hardening
    sequence: install
    restricted: false
    install:
      version: ${service_branch}
      template: templates/monitoring/monitoring_hardening.yml
      artifact_name: Clean_${service_branch}_Hardening