jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: Clean [${release_version}]. Upgrade to [${service_branch}]
    sequence: upgrade
    restricted: false
    install:
      version: ${release_version}
      template: templates/opensearch-service/opensearch_clean_all_on_sc.yml
      artifact_name: Clean_${release_version}_Upgrade_CURRENT
    upgrade:
      version: ${service_branch}
      template: templates/opensearch-service/opensearch_clean_all_on_sc.yml
      artifact_name: Clean_${release_version}_Upgrade_CURRENT
  ## ===============================================================================
  - name: Clean [${service_branch}]. Update with diff params
    sequence: upgrade
    restricted: false
    install:
      version: ${service_branch}
      template: templates/opensearch-service/opensearch_clean_all_on_sc.yml
      artifact_name: Clean_CURRENT_Update_Diff_Params
    upgrade:
      version: ${service_branch}
      template: templates/opensearch-service/opensearch_update_all_on_sc.yml
      artifact_name: Clean_CURRENT_Update_Diff_Params

  - name: Clean [${service_branch}] in Restricted mode
    sequence: install
    restricted: true
    install:
      version: ${service_branch}
      template: templates/opensearch-service/opensearch_clean_all_on_sc_restricted.yml
      artifact_name: Clean_CURRENT_Restricted

  - name: Clean [${service_branch}] on S3 storage
    sequence: install
    restricted: false
    install:
      version: ${service_branch}
      template: templates/opensearch-service/opensearch_clean_all_on_sc_s3.yml
      artifact_name: Clean_CURRENT_S3
      s3: true

  - name: Clean [${service_branch}] in TLS mode
    sequence: install
    restricted: false
    tls: true
    install:
      version: ${service_branch}
      template: templates/opensearch-service/opensearch_clean_all_on_sc_tls.yml
      artifact_name: Clean_CURRENT_TLS

  - name: Clean [${service_branch}] with Monitoring and Allure
    sequence: install
    restricted: false
    monitoring: true
    install:
      version: ${service_branch}
      template: templates/opensearch-service/opensearch_clean_all_on_sc_monitoring_allure.yml
      artifact_name: Clean_CURRENT_Monitoring
      s3: true
      allure: true
