jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: "Clean [${previous_version}], Upgrade to [${service_branch}]"
    install_version: "${previous_version}"
    core_template: "templates/pgskipper/patroni-core-quickstart-sample.yaml"
    services_template: "templates/pgskipper/patroni-services-quickstart-sample.yaml"
    upgrade_version: '${service_branch}'
    upgrade_core_template: "templates/pgskipper/patroni-core-quickstart-sample.yaml"
    upgrade_services_template: "templates/pgskipper/patroni-services-quickstart-sample.yaml"
    sequence: upgrade
    check_core_tests: true
    check_services_tests: true
    restricted: false
    tls: false
    artifact_name: "${image_replacement} Clean_${previous_version}_Upgrade_${service_branch}"
  ## ===========================================================================================================
  - name: "Clean [${service_branch}] TLS"
    install_version: "${service_branch}"
    core_template: "templates/pgskipper/patroni-core-tls.yaml"
    services_template: "templates/pgskipper/patroni-services-tls.yaml"
    sequence: install
    restricted: false
    tls: true
    artifact_name: "${image_replacement} Clean_CURRENT_TLS"

  - name: "Clean [${service_branch}]. Upgrade [${service_branch}] Diff Params"
    install_version: "${service_branch}"
    core_template: "templates/pgskipper/patroni-core-quickstart-sample.yaml"
    services_template: "templates/pgskipper/patroni-services-quickstart-sample.yaml"
    upgrade_version: "${service_branch}"
    upgrade_core_template: "templates/pgskipper/patroni-core-diffparams.yaml"
    upgrade_services_template: "templates/pgskipper/patroni-services-diffparams.yaml"
    sequence: upgrade
    restricted: false
    check_core_tests: true
    check_services_tests: true
    tls: false
    artifact_name: "${image_replacement} Clean_CURRENT_Upgrade_CURRENT_Diff_Params"

  - name: "Clean [${service_branch}] Full-AT"
    install_version: "${service_branch}"
    core_template: "templates/pgskipper/patroni-core-fullat.yaml"
    services_template: "templates/pgskipper/patroni-services-fullat.yaml"
    sequence: install
    restricted: false
    check_core_tests: true
    check_services_tests: true
    tls: false
    artifact_name: "${image_replacement} Clean_CURRENT_Full-AT"
  
  - name: "Clean [${release_version}] Restricted, Upgrade From [${release_version}] To [${service_branch}] Restricted"
    install_version: "${previous_version}"
    core_template: "templates/pgskipper/patroni-core-quickstart-sample.yaml"
    services_template: "templates/pgskipper/patroni-services-quickstart-sample.yaml"
    upgrade_version: "${service_branch}"
    upgrade_core_template: "templates/pgskipper/patroni-core-diffparams.yaml"
    upgrade_services_template: "templates/pgskipper/patroni-services-diffparams.yaml"
    sequence: upgrade
    restricted: true
    check_core_tests: true
    check_services_tests: true
    tls: false
    artifact_name: "${image_replacement} Clean_${release_version}_Restricted_Upgrade_From_${release_version}_To_${service_branch}_Restricted"

  - name: "Clean [${service_branch}] non-TLS, Upgrade [${service_branch}] with TLS"
    install_version: "${service_branch}"
    core_template: "templates/pgskipper/patroni-core-quickstart-sample.yaml"
    services_template: "templates/pgskipper/patroni-services-quickstart-sample.yaml"
    upgrade_version: "${service_branch}"
    upgrade_core_template: "templates/pgskipper/patroni-core-tls.yaml"
    upgrade_services_template: "templates/pgskipper/patroni-services-tls.yaml"
    sequence: upgrade
    restricted: false
    tls: true
    artifact_name: "${image_replacement} Clean_CURRENT_Upgrade_CURRENT_TLS"