jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: Clean [${release_version}], Upgrade to [${service_branch}]
    sequence: upgrade
    install:
      version: ${release_version}
      template: templates/rabbitmq-service/rabbitmq_clean_sc.yml
      artifact_name: Clean_${release_version}_Upgrade_CURRENT
    upgrade:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_clean_sc.yml
      artifact_name: Clean_${release_version}_Upgrade_CURRENT
  ## ===============================================================================
  - name: Clean [${service_branch}]. Update [${service_branch}] Diff Params
    sequence: upgrade
    install:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_clean_sc.yml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params
    upgrade:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_update_sc.yml
      artifact_name: Clean_CURRENT_Update_CURRENT_Diff_Params

  - name: Clean [${service_branch}] in Restricted mode
    sequence: install
    restricted: true
    install:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_clean_sc_restricted.yml
      artifact_name: Clean_CURRENT_Restricted

  - name: Clean [${service_branch}] on S3 storage
    sequence: install
    install:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_clean_sc_s3.yml
      artifact_name: Clean_CURRENT_S3
      s3: true

  - name: Clean [${service_branch}] on S3 storage in disasterRecovery mode
    sequence: install
    install:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_clean_sc_s3_drd.yml
      artifact_name: Clean_CURRENT_S3_DRD
      s3: true

  - name: Clean [${service_branch}] on S3 storage in disasterRecovery mode and TLS
    sequence: install
    tls: true
    install:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_clean_sc_s3_drd_tls.yml
      artifact_name: Clean_CURRENT_S3_DRD_TLS
      s3: true

  - name: Clean [${service_branch}] with Monitoring and Allure
    sequence: install
    monitoring: true
    install:
      version: ${service_branch}
      template: templates/rabbitmq-service/rabbitmq_clean_sc_monitoring_allure.yml
      artifact_name: Clean_CURRENT_full_at
      allure: true