jobs:
  ## A special configuration section for generating jobs for installing previous releases on the current version
  - purpose: automation
    name: "Clean [${release_version}], Upgrade to [${service_branch}]"
    install_version: '${release_version}'
    template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    upgrade_version: '${service_branch}'
    upgrade_template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    sequence: upgrade
    restricted: false
  ## ===============================================================================
  - name: "Clean [${service_branch}] Restricted"
    install_version: '${service_branch}'
    template: "templates/zookeeper-service/zookeeper_install_restricted_APP.yml"
    sequence: install
    restricted: true

  - name: "Clean [${service_branch}], Upgrade to [${service_branch}] Diff Params"
    install_version: '${service_branch}'
    template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    upgrade_version: '${service_branch}'
    upgrade_template: "templates/zookeeper-service/zookeeper_update_APP_k8s.yml"
    sequence: upgrade
    restricted: false

  - name: "Clean [${service_branch}] W/O Components, Upgrade [${service_branch}] All Components S3"
    install_version: '${service_branch}'
    template: "templates/zookeeper-service/zookeeper_install_minimal_APP_k8s.yml"
    upgrade_version: '${service_branch}'
    upgrade_template: "templates/zookeeper-service/zookeeper_install_s3_APP_k8s.yml"
    sequence: upgrade
    restricted: false
    storage: s3

  - name: "Clean [${service_branch}], Upgrade [${service_branch}] TLS"
    install_version: '${service_branch}'
    template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    upgrade_version: '${service_branch}'
    upgrade_template: "templates/zookeeper-service/zookeeper_install_tls_APP_k8s.yml"
    sequence: upgrade
    restricted: false
    tls: true

  - name: "Clean [${previous_version}] Restricted, Upgrade To [${service_branch}] Restricted"
    install_version: '${previous_version}'
    template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    upgrade_version: '${service_branch}'
    upgrade_template: "templates/zookeeper-service/zookeeper_install_APP_k8s.yml"
    sequence: upgrade
    restricted: true
