jobs:
  - name: Clean [${service_branch}] hardening
    sequence: install
    restricted: true
    monitoring: true
    install:
      version: ${service_branch}
      template: templates/zookeeper-service/zookeeper_install_hardening.yml
      artifact_name: Clean_CURRENT_Hardening
