name: 'Create Restricted Resources Action'
description: 'A GitHub Action to create resources before restricted installation'
inputs:
  service_name:
    description: |
      Helm release name
    required: true

  repository_name:
    description: |
      Service repository name (without organization prefix)
      Example: 'qubership-consul' for https://github.com/Netcracker/qubership-consul
    required: true

  path_to_chart:
    description: |
      Path to helm chart within service repository
      Example: 'charts/helm/consul-service'
    required: true

  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

runs:
  using: 'composite'
  steps:
#Create CRD
    - name: Create ClusterRoles
      shell: bash
      # language=bash
      run: |
        restricted_folder="qubership-test-pipelines/restricted/${{inputs.service_name}}"
        if [ ! -d "restricted_folder" ]; then
          echo "::warning::Files with restricted resources not found. Resources not created."
        else
          echo "Applying ClusterRoles..."
          kubectl create -f $restricted_folder/clusterRoles
        fi

    - name: Create ClusterRoleBindings
      shell: bash
      # language=bash
      run: |
        restricted_folder="qubership-test-pipelines/restricted/${{inputs.service_name}}"
        if [ ! -d "restricted_folder" ]; then
          echo "::warning::Files with restricted resources not found. Resources not created."
        else
          echo "Applying clusterRoleBindings..."
          kubectl create -f $restricted_folder/clusterRoleBindings
        fi

    - name: Create CRD
      shell: bash
      run: kubectl create -f ${{inputs.repository_name}}/${{inputs.path_to_chart}}/crds

    - name: Get CRD
      shell: bash
      run: kubectl get crd -n ${{inputs.namespace}} -oyaml

#Create Certificate
    - name: Install openssl
      shell: bash
      run: |
        sudo apt install openssl

    - name: Generate private key
      shell: bash
      run: |
        openssl genrsa -out restricted.key 2048

    - name: Generate CSR
      shell: bash
      run: |
        openssl req -new -key restricted.key -out restricted.csr -subj "/CN=restricted/O=dev-team"

    - name: Create CSR object
      shell: bash
      # language=bash
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: certificates.k8s.io/v1
        kind: CertificateSigningRequest
        metadata:
          name: restricted-csr
        spec:
          request: $(cat restricted.csr | base64 | tr -d '\n')
          signerName: kubernetes.io/kube-apiserver-client
          usages:
          - client auth
        EOF

    - name: Approve CSR
      shell: bash
      run: kubectl certificate approve restricted-csr

    - name: Retrieve certificate
      shell: bash
      run: kubectl get csr restricted-csr -o jsonpath='{.status.certificate}' | base64 --decode > restricted.crt

#Create Role and RB
    - name: Update yaml with Role
      shell: bash
      # language=bash
      run: >-
        python qubership-test-pipelines/python/replace_nc_in_template.py
        --path_to_file='qubership-test-pipelines/restricted/restricted-role.yml'
        --nc='${{inputs.namespace}}'

    - name: Update yaml with RoleBinding
      shell: bash
      # language=bash
      run: >-
        python qubership-test-pipelines/python/replace_nc_in_template.py
        --path_to_file='qubership-test-pipelines/restricted/restricted-rb.yml'
        --nc='${{inputs.namespace}}'

    - name: Create Role
      shell: bash
      run: kubectl create -f qubership-test-pipelines/restricted/restricted-role.yml

    - name: Create RoleBindings
      shell: bash
      run: kubectl create -f qubership-test-pipelines/restricted/restricted-rb.yml

#Add user to kubeconfig
    - name: Add user configuration
      shell: bash
      run: kubectl config set-credentials restricted --client-certificate=restricted.crt --client-key=restricted.key

    - name: Create context for user
      shell: bash
      run: kubectl config set-context restricted-context --cluster=kind-kind --namespace=${{inputs.namespace}} --user=restricted

    - name: Use context
      shell: bash
      run: kubectl config use-context restricted-context

    - name: Get config
      shell: bash
      run: kubectl config view --raw
