name: 'Helm Restricted Install Action'
description: 'A GitHub Action that installs services to kubernetes with restricted user'
inputs:
  path_to_template:
    description: 'Path to template'
    required: true
  service_branch:
    description: 'branch with release'
    required: true
  service_name:
    description: 'name with which service will be installed by helm'
    required: true
  repository_name:
    description: 'name of repository with service'
    required: true
  path_to_chart:
    description: 'path to helm chart in repository'
    required: true
  namespace:
    description: 'namespace to install service'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Echo
      run: echo creating resources
      shell: bash
#Create CRD
    - name: Create ClusterRoles
      run: |
        kubectl create -f qubership-test-pipelines/restricted/${{inputs.service_name}}/clusterRoles
      shell: bash

    - name: Create ClusterRoleBindings
      run: |
        kubectl create -f qubership-test-pipelines/restricted/${{inputs.service_name}}/clusterRoleBindings
      shell: bash

    - name: Create CRD
      run: |
        kubectl create -f ${{inputs.repository_name}}/${{inputs.path_to_chart}}/crds
      shell: bash

    - name: Get CRD
      run: kubectl get crd -n ${{inputs.namespace}} -oyaml
      shell: bash

#Create Certificate
    - name: Install openssl
      run: |
        sudo apt install openssl
      shell: bash

    - name: Generate private key
      run: |
        openssl genrsa -out restricted.key 2048
      shell: bash

    - name: Generate CSR
      run: |
        openssl req -new -key restricted.key -out restricted.csr -subj "/CN=restricted/O=dev-team"
      shell: bash

    - name: Create CSR object
      run: |
        cat <<EOF | kubectl apply -f -
        apiVersion: certificates.k8s.io/v1
        kind: CertificateSigningRequest
        metadata:
          name: restricted-csr
        spec:
          request: $(cat restricted.csr | base64 | tr -d '\n')
          signerName: kubernetes.io/kube-apiserver-client
          usages:
          - client auth
        EOF
      shell: bash

    - name: Approve CSR
      run: kubectl certificate approve restricted-csr
      shell: bash

    - name: Retrieve certificate
      run: kubectl get csr restricted-csr -o jsonpath='{.status.certificate}' | base64 --decode > restricted.crt
      shell: bash

#Create Role and RB
    - name: Update yaml with Role
      run: >-
        python qubership-test-pipelines/python/replace_nc_in_template.py 
        --path_to_file='qubership-test-pipelines/restricted/restricted-role.yml'
        --nc='${{inputs.namespace}}'
      shell: bash

    - name: Update yaml with RoleBinding
      run: >-
        python qubership-test-pipelines/python/replace_nc_in_template.py 
        --path_to_file='qubership-test-pipelines/restricted/restricted-rb.yml'
        --nc='${{inputs.namespace}}'
      shell: bash

    - name: Create Role
      run: kubectl create -f qubership-test-pipelines/restricted/restricted-role.yml
      shell: bash

    - name: Create RoleBindings
      run: kubectl create -f qubership-test-pipelines/restricted/restricted-rb.yml
      shell: bash

#Add user to kubeconfig
    - name: Add user configuration
      run: kubectl config set-credentials restricted --client-certificate=restricted.crt --client-key=restricted.key
      shell: bash

    - name: Create context for user
      run: kubectl config set-context restricted-context --cluster=kind-kind --namespace=${{inputs.namespace}} --user=restricted
      shell: bash

    - name: Use context
      run: kubectl config use-context restricted-context
      shell: bash

    - name: Get config
      run: kubectl config view --raw
      shell: bash
