apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-service-operator-kmm
rules:
  - apiGroups:
      - netcracker.com
    resources:
      - kmmconfigs
      - kmmconfigs/status
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
