name: "Check Status in CR"
description: "GitHub Action to status in custom resource.
It is necessary to check the installation status of services without Status Provisioner."
inputs:

  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

  max_attempts:
    description: |
      Maximum verification retries for test pod to be completed
    required: true
    default: 200

  timeout:
    description: |
      Delay between test pod check attempts
    required: true
    default: 10s

runs:
  using: 'composite'
  steps:
    - name: Create namespace
      # language=bash
      run: |
        for i in {1..${{inputs.max_attempts}}}; do
          cr_yaml=$(kubectl get ZooKeeperService zookeeper -n "${{inputs.namespace}}" -o yaml)
          condition=$(echo "$cr_yaml" | yq eval '.status.conditions[] | select(.reason == "ReconcileCycleStatus")' -o=json)
            if ! [[ -z "$condition" ]]; then
              echo $condition
              status=$(echo "$condition" | yq eval '.status' -)
              echo $status
              if [[ "$status" == 'True' ]]; then
                break
              fi
            fi
          sleep ${{inputs.timeout}}
        done
        kubectl get ZooKeeperService zookeeper -n "${{inputs.namespace}}" -o yaml
      shell: bash

