name: Get Certs Action
description: GitHub Action to get certs from secret
inputs:
  service_name:
    description: |
      Helm release name
    required: false
  secret_name:
    description: |
      Name of secret with certs
    required: true
  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

runs:
  using: composite
  steps:
    - name: Get secrets
      shell: bash
      env:
        SECRET_NAME: ${{ inputs.secret_name }}
        NAMESPACE: ${{ inputs.namespace }}
        RUNNER_TEMP: ${{ runner.temp }}
      # language=bash
      run: |
        # ▶️ Get secrets
        sudo snap install yq
        secret=$(kubectl get secret "${SECRET_NAME}" -oyaml -n "${NAMESPACE}")
        ca_crt=$(echo "$secret" | yq eval '.data["ca.crt"]' -)
        tls_crt=$(echo "$secret" | yq eval '.data["tls.crt"]' -)
        tls_key=$(echo "$secret" | yq eval '.data["tls.key"]' -)

        if [ -z "$ca_crt" ] || [ -z "$tls_crt" ] || [ -z "$tls_key" ]; then
          echo "ERROR: Failed to extract certificates!"
          exit 1
        fi

        echo "$ca_crt" > "${RUNNER_TEMP}/${SECRET_NAME}_ca_crt.txt"
        echo "$tls_crt" > "${RUNNER_TEMP}/${SECRET_NAME}_tls_crt.txt"
        echo "$tls_key" > "${RUNNER_TEMP}/${SECRET_NAME}_tls_key.txt"
