name: 'Generate ingress matrix'
description: 'Generates ingress config variations for all components'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        MATRIX_JSON=$(node <<'EOF'
        function pickRandom(arr) {
          return arr[Math.floor(Math.random() * arr.length)];
        }

        const components = [
          "prometheus",
          "pushgateway",
          "alertManager",
          "grafana",
          "vmSingle",
          "vmAuth",
          "vmAgent",
          "vmAlert",
          "vmAlertManager"
        ];

        const hostSources = ["host", "rules", "empty"];
        const tlsSources = [
          "tlsSecretName",
          "tlsBlock",
          "existingSecret",
          "generateCerts",
          "createSecret",
          "disabled"
        ];

        const result = [];

        for (const component of components) {
          const ingress_host_source = pickRandom(hostSources);
          const ingress_tls_source = pickRandom(tlsSources);

          result.push({
            component,
            ingress_host_source,
            ingress_tls_source,
            name: `${component}, ${ingress_host_source}, ${ingress_tls_source}`
          });
        }

        process.stdout.write(JSON.stringify(result));
        EOF
        )

        MATRIX_JSON=$(echo "$MATRIX_JSON" | jq -c '.')
        echo "matrix=$MATRIX_JSON" >> "$GITHUB_OUTPUT"
        echo "$MATRIX_JSON"
