name: "Add certs to Zookeeper secrets"
description: "GitHub Action to add certs to Zookeeper secrets"
runs:
  using: 'composite'
  steps:
    - name: Add Zookeeper CA CRT to template
      shell: bash
      run: >-
        python qubership-test-pipelines/python/update_yaml.py
        --file='qubership-test-pipelines/resources/zookeeper/zookeeper_tls_secret.yml'
        --path='data/ca.crt'
        --value="$(cat certs_artifacts/zookeeper-tls-secret_ca_crt.txt)"

    - name: Add Zookeeper TLS CRT to template
      shell: bash
      run: >-
        python qubership-test-pipelines/python/update_yaml.py
        --file='qubership-test-pipelines/resources/zookeeper/zookeeper_tls_secret.yml'
        --path='data/tls.crt'
        --value="$(cat certs_artifacts/zookeeper-tls-secret_tls_crt.txt)"

    - name: Add Zookeeper TLS KEY to template
      shell: bash
      run: >-
        python qubership-test-pipelines/python/update_yaml.py
        --file='qubership-test-pipelines/resources/zookeeper/zookeeper_tls_secret.yml'
        --path='data/tls.key'
        --value="$(cat certs_artifacts/zookeeper-tls-secret_tls_key.txt)"

    - name: Add Backup Daemon CA CRT to template
      shell: bash
      run: >-
        python qubership-test-pipelines/python/update_yaml.py
        --file='qubership-test-pipelines/resources/zookeeper/zookeeper_backup_daemon_tls_secret.yml'
        --path='data/ca.crt'
        --value="$(cat certs_artifacts/zookeeper-backup-daemon-tls-secret_ca_crt.txt)"

    - name: Add Backup Daemon TLS CRT to template
      shell: bash
      run: >-
        python qubership-test-pipelines/python/update_yaml.py
        --file='qubership-test-pipelines/resources/zookeeper/zookeeper_backup_daemon_tls_secret.yml'
        --path='data/tls.crt'
        --value="$(cat certs_artifacts/zookeeper-backup-daemon-tls-secret_tls_crt.txt)"

    - name: Add Backup Daemon TLS KEY to template
      shell: bash
      run: >-
        python qubership-test-pipelines/python/update_yaml.py
        --file='qubership-test-pipelines/resources/zookeeper/zookeeper_backup_daemon_tls_secret.yml'
        --path='data/tls.key'
        --value="$(cat certs_artifacts/zookeeper-backup-daemon-tls-secret_tls_key.txt)"
