name: 'Custom GitHub Action'
description: 'A GitHub Action that installs services to kubernetes'
inputs:
#  service_branch:
#    description: 'branch name in repository with service'
#    required: true
#  pipeline_branch:
#    description: 'name of branch with your pipeline in qubership-test-pipelines'
#    required: true
#    default: 'main'
  repository_name:
    description: 'name of repository with service'
    required: true
    default: 'qubership-consul'
  namespace:
    description: 'namespase to install service'
    required: true
    default: 'consul'

runs:
  using: 'composite'
  steps:
    - name: Checkout pipeline
      uses: actions/checkout@v4
      with:
        ref: '${{inputs.pipeline_branch}}'
        repository: 'Netcracker/qubership-test-pipelines'
        path: 'qubership-test-pipelines'
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: '${{inputs.service_branch}}'
        repository: 'Netcracker/${{inputs.repository_name}}'
        path: '${{inputs.repository_name}}'
    - name: Run kind
      uses: Netcracker/qubership-test-pipelines/actions/shared/run_kind@update_actions
    - name: Create namespace
      run: kubectl create namespace '${{inputs.namespace}}'
      shell: bash
