---
{{ if eq .Values.PAAS_PLATFORM "KUBERNETES" }}
apiVersion: {{ include "sm-.ingress.apiVersion" . }}
kind: Ingress
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  rules:
  - host: {{ .Values.ingressName }}
    http:
      paths:
      - path: /
        pathType: ImplementationSpecific
        backend:
          {{- if eq ( include "sm-.ingress.apiVersion" . ) "networking.k8s.io/v1beta1" }}
          serviceName: {{ .Values.name }}
          servicePort: 80
          {{- else if eq ( include "sm-.ingress.apiVersion" . ) "networking.k8s.io/v1" }}
          service:
            name: {{ .Values.name }}
            port:
              number: 80
          {{- end }}
{{ end }}