kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: full-access-deploy-user
    namespace: <namespace>
subjects:
  - kind: ServiceAccount
    #name: restricted-sa
    name: kind-kind
roleRef:
    apiGroup: rbac.authorization.k8s.io
    name: full-access
    kind: Role
