kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: restricted-role-binding
  namespace: <namespace>
subjects:
- kind: User
  name: restricted
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: restricted-role
  apiGroup: rbac.authorization.k8s.io
