name: 'Custom GitHub Action'
description: 'A GitHub Action that takes an input and returns the square of the number'
#inputs:
#  namespace:
#    description: 'namespace where service is installed'
#    required: true

runs:
  using: 'composite'
  steps:
    - name: Get pods
      run: 'kubectl get pods -n ${{env.namespace}}'
      shell: bash
#    - name: Get provisioner logs
#      run: |
#        pods=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}}  | tr -s '\r\n' ' ')
#        IFS=$' ' read -a pods_list <<< "$pods"
#        echo "$pods"
#        for pod in "${pods_list[@]}"; do
#          if [[ $pod == *"provisioner"* ]]; then
#            provisioner_pod=$pod
#          fi
#        done
#        echo "provisioner_pod=$provisioner_pod"
#        for i in {1..${{env.max_attempts}}}; do
#          status=$(kubectl get pod $provisioner_pod -n ${{env.namespace}} -o jsonpath="{.status.phase}")
#          echo "status=$status"
#          if [[ "$status" == 'Succeeded' ]]; then
#            break
#          fi
#          sleep ${{env.timeout}}
#        done
#        if [[ "$status" != 'Succeeded' ]]; then
#          echo $provisioner_pod pod has not Succeeded status
#        fi
#        echo PROVISIONER LOGS:
#        kubectl logs $provisioner_pod -n ${{env.namespace}}
#        logs=$(kubectl logs $provisioner_pod -n ${{env.namespace}})
#        if [[ $logs != *"Failed components statuses are []"* ]]; then
#          echo Not all components are in succeed status after ${{env.max_attempts}} attempts
#          echo PODS:
#          kubectl get pods -n ${{env.namespace}}
#          echo EVENTS:
#          kubectl events -n ${{env.namespace}}
#          exit 1
#        fi
#      shell: bash

#    - name: Get yaml from pods
#      run: |
#        pods=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}})
#        pods_str=$(echo "$pods" | tr $'\n' ' ')
#        echo "pods: $pods_str"
#        IFS=' ' read -ra elements <<< "$pods_str"
#        for element in "${elements[@]}"; do
#            status=$(kubectl get pod $element -o jsonpath="{.status.phase}")
#            echo $status
#            if [[ $element == *"consul"* ]]; then
#              kubectl get pod "$element" -n ${{env.namespace}} -oyaml
#            fi
#        done
#      shell: bash

    - name: Get logs from pods
      run: |
        pods=$(kubectl get pods --no-headers -o custom-columns=":metadata.name" -n ${{env.namespace}})
        pods_str=$(echo "$pods" | tr $'\n' ' ')
        echo "pods: $pods_str"
        IFS=' ' read -ra elements <<< "$pods_str"
        for element in "${elements[@]}"; do
            status=$(kubectl get pod $element -o jsonpath="{.status.phase}")
            echo $status
            if [[ $element == *"consul"* ]]; then
              echo "$element"
              if [[ $element != *"consul-acl"* ]]; then
                #kubectl get pod "$element" -n ${{env.namespace}} -oyaml
                #echo "$element LOGS:"
                kubectl logs "$element" -n ${{env.namespace}} -c client-acl-init
              fi
            fi
        done
      shell: bash
