name: "Helm deploy Action"
description: "GitHub Action to install/upgrade services using Helm"
inputs:
  deploy_mode:
    description: |
      Deployment mode:
      - 'install' for clean installation
      - 'upgrade' to upgrade an existing release
    required: true
    default: 'install'

  restricted:
    description: |
      - 'true': helm installation by user with restricted rights
      - 'false': helm installation by cluster admin user
    required: true
    default: 'false'
    type: boolean

  path_to_template:
    description: |
      Path to template file in qubership-test-pipelines repository
      Example: 'templates/consul-service/consul_clean_infra_passport.yml'
    required: true

  service_branch:
    description: |
      Branch in service repository
    required: true

  service_name:
    description: |
      Helm release name
    required: true

  repository_name:
    description: |
      Service repository name
      Example: 'Netcracker/qubership-consul' for https://github.com/Netcracker/qubership-consul
    required: true

  path_to_chart:
    description: |
      Path to helm chart within service repository
      Example: 'charts/helm/consul-service'
    required: true

  namespace:
    description: |
      Kubernetes namespace for service installation
    required: true

  resource_folder:
    description: |
      Folder with resources for creating before installation
    required: true

  image_replacement:
    description: "New image name (e.g., pgskipper-patroni-17)"
    required: false
    default: ''

  image_block_name:
    description: "Name of the block in values.yaml (e.g., patroni, kafka)"
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: '${{inputs.service_branch}}'
        repository: '${{inputs.repository_name}}'
        path: '${{inputs.repository_name}}'

    - name: Create namespace
      if: inputs.deploy_mode == 'install'
      shell: bash
      # language=bash
      run: |
        if ! kubectl get namespace ${{inputs.namespace}} >/dev/null 2>&1; then
        kubectl create namespace ${{inputs.namespace}}
        else
        echo "Namespace '${{inputs.namespace}}' already exists"
        fi

    - name: Create resources
      if: inputs.resource_folder != ''
      shell: bash
      # language=bash
      run: |
        folder="qubership-test-pipelines/${{inputs.resource_folder}}"
        files=($(find "$folder" -type f))
        echo $files
        for file in "${files[@]}"; do
          echo "Applying $file"
          kubectl create -f "$file"
        done

    - name: Replace CRDs
      shell: bash
      # language=bash
      run: |
        # ▶️ Replace CRDs
        cd "${{inputs.repository_name}}/${{inputs.path_to_chart}}"
        if [ -d "./crds" ]; then
          echo "CRDs directory exists"
          for file in ./crds/*; do
            if [ -f "$file" ]; then
              echo "Processing file: $file"
              CRD_NAME=$(yq e '.metadata.name' "$file" 2>/dev/null)

              if [ -z "$CRD_NAME" ]; then
                echo "::error::Could not extract CRD name from $file"
                exit 1
              fi

              echo "Found CRD: $CRD_NAME"
              if kubectl get crd "$CRD_NAME" > /dev/null 2>&1; then
                  echo "CRD $CRD_NAME already exists. Updating..."
                  kubectl replace -f $file
              else
                  echo "CRD $CRD_NAME doesn't exist. Creating..."
                  kubectl create -f $file
              fi
            fi
          done
        else
          echo "::error::Directory with CRDs not found!"
          exit 1
        fi

    - name: Create restricted resources
      if: inputs.restricted == 'true'  && inputs.deploy_mode == 'install'
      uses: ./qubership-test-pipelines/actions/shared/create_restricted_resources
      with:
        service_name: ${{inputs.service_name}}
        repository_name: ${{inputs.repository_name}}
        path_to_chart: ${{inputs.path_to_chart}}
        namespace: ${{inputs.namespace}}

    - name: Copy template
      shell: bash
      # language=bash
      run: |
        cp qubership-test-pipelines/${{inputs.path_to_template}} ${{inputs.repository_name}}/${{inputs.path_to_chart}}

    - name: Check if version is release
      id: check-release
      shell: bash
      # language=bash
      run: |
        # ▶️ Check if version is release
        if [[ "${{inputs.service_branch}}" =~ v?[0-9]+\.[0-9]+\.[0-9]+ ]]; then
          echo "${{inputs.service_branch}} is release version"
          echo "is_release=true" >> $GITHUB_OUTPUT
        else
          echo "${{inputs.service_branch}} is not release version"
          echo "is_release=false" >> $GITHUB_OUTPUT
        fi

    - name: Override image in values.yaml
      if: inputs.image_replacement != '' && inputs.image_block_name != ''
      shell: bash
      # language=bash
      run: |
        target_file="${{inputs.repository_name}}/${{inputs.path_to_chart}}/values.yaml"
        echo "=== [DEBUG] File: $target_file | Block: ${{ inputs.image_block_name }} | Image: ${{ inputs.image_replacement }} ==="
        if [ ! -f "$target_file" ]; then
          echo "::error::File not found"
          exit 1
        fi
        echo "--- BEFORE ---"
        grep -A 5 "${{ inputs.image_block_name }}:" "$target_file"  true
        sed -i "/${{ inputs.image_block_name }}:/,/dockerImage:/ s|\(dockerImage: .*/\)[^:]*\(:\)|\1${{ inputs.image_replacement }}\2|" "$target_file"
        echo "--- AFTER ---"
        grep -A 5 "${{ inputs.image_block_name }}:" "$target_file"  true
        echo "=== [DEBUG] Done ==="

    - name: Override version
      if: inputs.image_replacement != ''
      shell: bash
      # language=bash
      run: |
        target_file="${{inputs.repository_name}}/${{inputs.path_to_chart}}/values.yaml"
        echo "=== [DEBUG] Starting image replacement ==="
        echo "File: $target_file"
        echo "New image name: ${{ inputs.image_replacement }}"
        if [ ! -f "$target_file" ]; then
          echo "::error::Target file $target_file not found!"
          exit 1
        fi
        echo "--- [DEBUG] Content BEFORE change (patroni block) ---"
        grep -A 5 "patroni:" "$target_file" || echo "patroni block not found"
        sed -i '/patroni:/,/dockerImage:/ s|\(dockerImage: .*/\)[^:]*\(:\)|\1${{ inputs.image_replacement }}\2|' "$target_file"
        echo "--- [DEBUG] Content AFTER change (patroni block) ---"
        if grep -A 5 "patroni:" "$target_file" | grep -q "${{ inputs.image_replacement }}"; then
          grep -A 5 "patroni:" "$target_file"
          echo "=== [DEBUG] Success: Image replaced successfully ==="
        else
          echo "::warning::Image replacement might have failed. Check the pattern."
          grep -A 5 "patroni:" "$target_file"
        fi
  
    - name: Update versions in values
      id: update-versions
      if: ${{ steps.check-release.outputs.is_release == 'false' }}
      uses: netcracker/qubership-workflow-hub/actions/charts-values-update-action@d558e10a6537924292e7dd7ff4109c2bda9b406e #v2.0.5
      with:
        release-version: ${{steps.replace_slash.outputs.service_branch_updated}}
        config-file: .github/charts-values-update-config.yaml
        create-release-branch: "false"
        version-replace-method: 'parse'
        working-directory: ${{inputs.repository_name}}
        chart-version: ${{github.run_number}}.${{github.run_attempt}}.${{github.run_id}}
        default-tag: 'main'

    - name: Install/update service with helm
      shell: bash
      # language=bash
      run: |
        # ▶️ ${{inputs.deploy_mode}} ${{inputs.service_name}} with Helm
        template_name=$(basename "${{inputs.path_to_template}}")
        echo $template_name
        cd ${{inputs.repository_name}}/${{inputs.path_to_chart}}
        if [[ "${{inputs.restricted}}" == "false" ]]; then
          helm ${{inputs.deploy_mode}} ${{inputs.service_name}} . -f $template_name -n ${{inputs.namespace}} --timeout 10m
        else
          helm ${{inputs.deploy_mode}} ${{inputs.service_name}} . -f $template_name -n ${{inputs.namespace}} --timeout 10m --skip-crds
        fi

    - name: Get docker images
      shell: bash
      # language=bash
      run: |
        # ▶️ Get docker images
        kubectl get pods -n ${{inputs.namespace}} -o go-template --template="{{range .items}}{{range .spec.containers}}{{.image}} {{end}}{{end}}"

    - name: Use default context
      if: inputs.restricted == 'true'
      shell: bash
      # language=bash
      run: kubectl config use-context kind-kind
