name: Install Consul

on:
  workflow_call:
    inputs:
      service_branch:
        required: false
        type: string

env:
  max_attempts: 60
  timeout: '10s'
  repository_name: 'qubership-consul'
  path_to_chart: 'charts/helm/consul-service'
  namespace: 'consul'
  service_name: 'consul'
  components: 'integrationTests'

jobs:
  Test-job1:
    runs-on: ubuntu-latest
    name: Test job1
    steps:
    - name: Run kind
      uses: Netcracker/qubership-test-pipelines/actions/run_kind@main
    - name: Install consul
      uses: Netcracker/qubership-test-pipelines/actions/helm_install@restricted_install
      with:
        path_to_template: 'templates/consul-service/consul_clean_all_on_sc_restricted1.yml'
        service_branch: '${{inputs.service_branch}}'
    - name: Check status provisioner
      uses: Netcracker/qubership-test-pipelines/actions/check_status_provisioner@main
    - name: Check tests
      uses: Netcracker/qubership-test-pipelines/actions/validate_tests_result@main
  Test-job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Run kind
        uses: Netcracker/qubership-test-pipelines/actions/run_kind@main
      - name: Install consul in restricted mode
        uses: Netcracker/qubership-test-pipelines/actions/helm_install_restricted@restricted_install
        with:
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_restricted.yml'
          service_branch: 'improvement/run_tests'
      - name: Check status provisioner
        uses: Netcracker/qubership-test-pipelines/actions/check_status_provisioner@main
      - name: Check tests
        uses: Netcracker/qubership-test-pipelines/actions/validate_tests_result@main

