name: Install Consul

on:
  workflow_call:
    inputs:
      service_branch:
        required: false
        type: string

env:
  max_attempts: 60
  timeout: '10s'
  repository_name: 'qubership-consul'
  path_to_chart: 'charts/helm/consul-service'
  namespace: 'consul'
  service_name: 'consul'
  components: 'integrationTests'

jobs:
  Test-job1:
    runs-on: ubuntu-latest
    name: Test job1
    steps:
    - name: Run kind
      uses: Netcracker/qubership-test-pipelines/actions/run_kind@main
    - name: Checkout pipeline
      uses: actions/checkout@v4
      with:
        ref: 'restricted_install'
        repository: 'Netcracker/qubership-test-pipelines'
        path: 'qubership-test-pipelines'
    - name: Checkout repo
      uses: actions/checkout@v4
      with:
        ref: 'main'
        repository: 'Netcracker/qubership-monitoring-operator'
        path: 'qubership-monitoring-operator'
    - name: Create namespaces
      run: kubectl create namespace monitoring
    #- name: Copy template
      #run: |
        #cp qubership-test-pipelines/templates/monitoring/vm_with_smoke_at.yml qubership-test-pipelines/templates/monitoring
#      shell: bash
#      - name: Install service with helm
#        run: helm install monitoring qubership-monitoring-operator/charts/qubership-monitoring-operator  -n monitoring --timeout 10m
#    - name: Install monitoring with helm
#      run: |
#        IFS=$'/' read -a path <<< "qubership-test-pipelines/templates/monitoring/vm_with_smoke_at.yml"
#        template_name=${path[-1]}
#        echo $template_name
#        cd qubership-test-pipelines/templates/monitoring
#        helm install monitoring . -f $template_name -n monitoring --timeout 10m
#      shell: bash
#    - name: Get pods
#      run: 'kubectl get pods -n ${{env.namespace}}'
#    - name: Sleep
#      run: sleep 3m
#    - name: Get pods
#      run: 'kubectl get pods -n ${{env.namespace}}'
#    - name: Get events
#      run: 'kubectl events -n ${{env.namespace}}'
    - name: Install consul
      uses: Netcracker/qubership-test-pipelines/actions/helm_install@restricted_install
      with:
        path_to_template: 'templates/consul-service/consul_clean_all_on_sc_restricted1.yml'
        service_branch: '${{inputs.service_branch}}'
    - name: Check status provisioner
      uses: Netcracker/qubership-test-pipelines/actions/check_status_provisioner@main
    - name: Check tests
      uses: Netcracker/qubership-test-pipelines/actions/validate_tests_result@main
  Test-job:
    runs-on: ubuntu-latest
    name: Test job
    steps:
      - name: Run kind
        uses: Netcracker/qubership-test-pipelines/actions/run_kind@main
      - name: Install consul in restricted mode
        uses: Netcracker/qubership-test-pipelines/actions/helm_install_restricted@restricted_install
        with:
          path_to_template: 'templates/consul-service/consul_clean_all_on_sc_restricted.yml'
          service_branch: 'improvement/run_tests'
      - name: Check status provisioner
        uses: Netcracker/qubership-test-pipelines/actions/check_status_provisioner@restricted_install
      - name: Check tests
        uses: Netcracker/qubership-test-pipelines/actions/validate_tests_result@restricted_install

