name: PR Auto-Assignment
run-name: "Assigning reviewers for PR #${{ github.event.pull_request.number }}"
on:
  pull_request_target:
    types: [opened, reopened, synchronize]
    branches:
      - main

permissions:
  contents: read

jobs:
  pr-auto-assign:
    name: "Auto-assign Reviewers to PR #${{ github.event.pull_request.number }}"
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Check if PR is from a fork
        env:
          HEAD_FULL_NAME: ${{ github.event.pull_request.head.repo.full_name }}
          BASE_FULL_NAME: ${{ github.event.pull_request.base.repo.full_name }}
        run: |
          if [ "${HEAD_FULL_NAME}" != "${BASE_FULL_NAME}" ]; then
            echo "⚠️ Pull request is from a fork — skipping assignee assignment (no write permissions)."
            exit 0
          fi

      - name: Checkout Repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Assign Reviewers
        uses: netcracker/qubership-workflow-hub/actions/pr-assigner@8b1f50086b028c0ad22dafd33352e2166189b742 # v2.7.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
